$ ->
  $('#jstree_categories').jstree()
$ ->
  $('#jstree_categories').jstree({
    'core' : {
      'check_callback' : true,
      'data' : {
        'url' : (node) ->
          return 'categories.json' # GET /categoris.json を実行する
      }
    },
    "plugins" : [ "dnd" ]
  })

$ ->
  $('#jstree').jstree()
$ ->
  $('#jstree').jstree({
    'core' : {
      'check_callback' : true,
      'data' : {
        'url' : (node) ->
          # return 'categories.json' # GET /categoris.json を実行する
      }
    },
    "plugins" : [ "dnd" ]
  })

$('#jstree_categories').on "move_node.jstree", (e, n) ->
    # Todo サーバーのデータを更新するようにする
    console.log "#{n.old_parent}:#{n.old_position} -> #{n.parent}:#{n.position}"

$('#jstree_demo_div').on 'changed.jstree', (e, data) ->
  console.log data.selected
  return

$('body').on 'click', '#list li', (e) ->
  e.preventDefault()
  # $(this).css 'background', '#f69'
  alert 'aaaa'
  return


$('#jstree').on('changed.jstree', (e, data) ->
  i = undefined
  j = undefined
  r = []
  i = 0
  j = data.selected.length
  while i < j
    r.push data.instance.get_node(data.selected[i]).text
    i++
  $('#event_result').html 'Selected: ' + r.join(', ')
  return
).jstree()

# ---
# generated by js2coffee 2.2.0
